version: '3'
services:
  hadoop:
    image: apache/hadoop:3.4.1
    container_name: hadoop-container
    hostname: hadoop
    ports:
      - "9870:9870"   # NameNode HTTP UI
      - "9864:9864"   # DataNode HTTP UI
      - "8088:8088"   # YARN ResourceManager
      - "9000:9000"   # NameNode
    environment:
      HADOOP_HOME: /opt/hadoop-3.4.1
    command: >
      bash -c "
      hdfs namenode -format &&
      $${HADOOP_HOME}/sbin/start-dfs.sh &&
      $${HADOOP_HOME}/sbin/start-yarn.sh &&
      tail -f /dev/null
      "