apiVersion: v1
kind: NodeConfig
kubeletArguments:
  cgroup-driver: ["cgroupfs"]
  max-pods: ["40"]
  pod-manifest-path: ["/etc/origin/node/pods"]
  node-labels: ["region=infra,zone=default"]
servingInfo:
  bindAddress: "0.0.0.0:10250"
  certFile: "/etc/origin/node/server.crt"
  clientCA: "/etc/origin/node/ca.crt"
  keyFile: "/etc/origin/node/server.key"
masterClientConnection:
  kubeConfig: "/etc/origin/node/node.kubeconfig"
volumeDirectory: "/var/lib/origin/openshift.local.volumes"
imageConfig:
  format: "openshift/origin-${component}:${version}"
networkConfig:
  networkPluginName: "redhat/openshift-ovs-subnet"
dnsIP: "172.30.0.10"